"""Add Comment model and update Post model with book_id and rating

Revision ID: 2fa9b48c796f
Revises: ca614ff09a67
Create Date: 2026-01-17 02:18:16.310627

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2fa9b48c796f'
down_revision = 'ca614ff09a67'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('comment',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('post_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['post_id'], ['post.id'], name='fk_comment_post'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name='fk_comment_user'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('post', schema=None) as batch_op:
        batch_op.add_column(sa.Column('book_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('rating', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('created_at', sa.DateTime(), nullable=False))
        batch_op.create_foreign_key('fk_post_book', 'book', ['book_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('post', schema=None) as batch_op:
        batch_op.drop_constraint('fk_post_book', type_='foreignkey')
        batch_op.drop_column('created_at')
        batch_op.drop_column('rating')
        batch_op.drop_column('book_id')

    op.drop_table('comment')
    # ### end Alembic commands ###
