"""Add checkout_date and checked_out_by to Book model

Revision ID: 6ac6ce52f099
Revises: 57a03b902dba
Create Date: 2026-01-17 01:19:52.777750

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6ac6ce52f099'
down_revision = '57a03b902dba'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('book', schema=None) as batch_op:
        batch_op.add_column(sa.Column('checkout_date', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('checked_out_by', sa.Integer(), nullable=True))
        batch_op.create_foreign_key('fk_book_user', 'user', ['checked_out_by'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('book', schema=None) as batch_op:
        batch_op.drop_constraint('fk_book_user', type_='foreignkey')
        batch_op.drop_column('checked_out_by')
        batch_op.drop_column('checkout_date')

    # ### end Alembic commands ###
