"""Add reading preferences and fix relationships

Revision ID: a7e819ce0bf6
Revises: 06d022b52b00
Create Date: 2026-01-17 04:17:46.203949

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a7e819ce0bf6'
down_revision = '06d022b52b00'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('post', schema=None) as batch_op:
        batch_op.create_foreign_key('fk_post_book_id', 'book', ['book_id'], ['id'])

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('waitlist_book_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('reading_preferences', sa.String(length=500), nullable=True))
        batch_op.create_foreign_key('fk_user_waitlist_book_id', 'book', ['waitlist_book_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_constraint('fk_user_waitlist_book_id', type_='foreignkey')
        batch_op.drop_column('reading_preferences')
        batch_op.drop_column('waitlist_book_id')

    with op.batch_alter_table('post', schema=None) as batch_op:
        batch_op.drop_constraint('fk_post_book_id', type_='foreignkey')

    # ### end Alembic commands ###
