"""Add reading goal to user

Revision ID: c9d4e5f6g7h8
Revises: b8c3d4e5f6a7
Create Date: 2026-01-17 05:00:00.000000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c9d4e5f6g7h8'
down_revision = 'b8c3d4e5f6a7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('reading_goal', sa.Integer(), nullable=False, server_default='12'))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('reading_goal')

    # ### end Alembic commands ###
